name: Readme Update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # 1시간마다 한 번씩 실행 (UTC 시간 기준)
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm ci
          npm install rss-parser

      - name: Update README
        run: npm start

      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit README
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --local user.email "jamine0316@naver.com"
          git config --local user.name "horaeng333"
          git add .
          git commit -m "Update README.md"
          git push origin main